spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.d15822df8d4ec5a8
            client-secret: 63758741a655fa0fe83a874b04d5798c78b18327
  data:
    cassandra:
      keyspace-name: main
      username: TDbpbNPmshfKqtFkoxMcSQbJ
      password: E7oLL81GUGEgL5BOhfpgYe9..7Eo2IGjrD3TqRum9vlkq1FZ7iF45idW6DHmp-5l5Cp-MOm,keofZ7RT7vX0qXM5ZTDqGQ47ZgIQ7TPIE67+HEMqHT+GJ.-UDgkcn46h
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: betterreads


datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra:
  db: 
    id: 0c963752-c756-4510-8754-5bb2c31d182d-1
    region: us-east1
    keyspace: main
    application:
      token: <astra-app-token>          